=== MIPS/meos/doc/module.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT module (description, imports*, interface)>
<!ATTLIST module
	modtype (Functional | System | Special) #REQUIRED
	name CDATA #REQUIRED
	prefix CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT enum (item)+>
<!ELEMENT item (#PCDATA | par | enum | emph | bold | code | nl)*>
<!ATTLIST item
	val CDATA #REQUIRED
>
<!ELEMENT par EMPTY>
<!ELEMENT imports (#PCDATA)>
<!ELEMENT prologue ANY>
<!ELEMENT epilogue ANY>
<!ELEMENT interface (prologue?, include*, define*, typedef*, var*, func*, postinclude*, epilogue?)>
<!ELEMENT include (#PCDATA)>
<!ATTLIST include
	lib (Y | N) #REQUIRED
>
<!ELEMENT postinclude (#PCDATA)>
<!ATTLIST postinclude
	lib (Y | N) #REQUIRED
>
<!ELEMENT define (#PCDATA | par | enum | emph | bold | code | c)*>
<!ATTLIST define
	vis (concrete | virtual) "concrete"
>
<!ELEMENT typedef (#PCDATA | par | enum | emph | bold | code | c)*>
<!ATTLIST typedef
	vis (public | private | anonymous | virtual | virpriv | viranon) #IMPLIED
>
<!ELEMENT var (#PCDATA | par | enum | emph | bold | code)*>
<!ATTLIST var
	type CDATA #REQUIRED
	decl CDATA #REQUIRED
>
<!ELEMENT func ((voidargs | (arg*, varargs?)), return, entry?, exit?, resources?, description, limitations?)>
<!ELEMENT entry (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT exit (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT resources (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT varargs EMPTY>
<!ELEMENT voidargs EMPTY>
<!ATTLIST func
	name CDATA #REQUIRED
	quals CDATA #IMPLIED
	vis (concrete | virtual | private | virpriv) "concrete"
	return (Y | N) "Y"
>
<!ELEMENT arg (#PCDATA | par | enum | emph | bold | code)*>
<!ATTLIST arg
	type CDATA #REQUIRED
	name CDATA #REQUIRED
	traceable (Y | N) "N"
>
<!ELEMENT return (#PCDATA | par | enum | emph | bold | code)*>
<!ATTLIST return
	type CDATA #REQUIRED
>
<!ELEMENT limitations (arglimit*, precondition*, postcondition*)>
<!ELEMENT c (#PCDATA | tab | nl | parahead | paratail)*>
<!ELEMENT emph (#PCDATA)>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT code (#PCDATA | tab | nl)*>
<!ELEMENT tab EMPTY>
<!ELEMENT nl EMPTY>
<!ELEMENT parahead EMPTY>
<!ELEMENT paratail EMPTY>
<!ELEMENT arglimit (#PCDATA | code | nl)*>
<!ATTLIST arglimit
	argname CDATA #REQUIRED
	min CDATA #IMPLIED
	max CDATA #IMPLIED
	mult CDATA #IMPLIED
	align (0 | 1 | 2 | 4 | 8 | pow2) "0"
	num (0 | Q63 | Q31 | Q23 | Q15 | Q7) "0"
>
<!ELEMENT precondition (#PCDATA)>
<!ELEMENT postcondition (#PCDATA)>

=== MIPS/meos/support/1/drivers/dwethgmac/dwethgmac.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="dwethgmac" prefix="DWETHGMAC" modtype="Special">
	<description>DesignWare Ethernet GMAC LWIP driver</description>
	<imports>kernel</imports>
	<imports>lwip</imports>
	<interface>
		<include lib="Y">stdio.h</include>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<include lib="N">lwip/netif.h</include>
		<typedef vis="private"><c>struct DWETHGMAC_tag DWETHGMAC_T</c>(Incomplete) DWETHGMAC system object definition.</typedef>
		<func name="DWETHGMAC_dtInit">
			<arg type="DWETHGMAC_T *" name="dwethgmac" traceable="Y">Pointer to DWETHGMAC system object.</arg>
			<arg type="IRQ_DESC_T *" name="irq">IRQ descriptor for specified DWETHGMAC.</arg>
			<return type="void"/>
			<limitations>
				<precondition>((dwethgmac != NULL) &amp;&amp; (irq != NULL))</precondition>
			</limitations>
			<description>Initialises the DWETHGMAC described by <code>dwethgmac</code> based on the provided configuration.
			</description>
		</func>
		<epilogue>
typedef uint32_t DWETHGMAC_DMADESC_T[4];

/* complete the DWETHGMAC_T definition... */
struct DWETHGMAC_tag {
	uintptr_t	pAddr;
	uint8_t*	regs;
	uint8_t mac[6];
	KRN_TIMER_T phyTimer;
	uint8_t rxBuf[CONFIG_DRIVER_DWETHGMAC_NUM_DESCS][2048] __attribute__ ((aligned (32)));
	uint8_t txBuf[CONFIG_DRIVER_DWETHGMAC_NUM_DESCS][2048] __attribute__ ((aligned (32)));
	uint32_t txReset0;
	uint32_t txReset1;
	DWETHGMAC_DMADESC_T txDesc[CONFIG_DRIVER_DWETHGMAC_NUM_DESCS] __attribute__ ((aligned (32)));
	uint32_t txi __attribute__ ((aligned (32)));
	DWETHGMAC_DMADESC_T rxDesc[CONFIG_DRIVER_DWETHGMAC_NUM_DESCS] __attribute__ ((aligned (32)));
	struct netif netif __attribute__ ((aligned (32)));
};
		</epilogue>
	</interface>
</module>

=== MIPS/meos/support/3/newtron/newtron.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../doc/doc.xsl"?>
<module name="Newtron" prefix="Newtron" modtype="Special">
	<description>Newtron - see http://mynewt.apache.org/os/modules/fs/nffs/nffs/. Once a <code>MASS</code> compatible device has been mounted with <code>NEWTRON_init</code>, simply use as usual. All libraries and include paths should be set up by meos-config.</description>
	<interface>
		<prologue>
			#include &lt;stdlib.h&gt;
			#include &lt;stdint.h&gt;
			#include "newtron/fs/fs/fs.h"
			#include "newtron/fs/fs/fs_if.h"
			#include "newtron/fs/nffs/nffs.h"
			#include "newtron/hw/bsp/bsp.h"

			#if !defined( H_NFFS_PRIV_) &amp;&amp; !defined(_OS_H) &amp;&amp; !defined(_OS_MUTEX_H_)
			#define NFFS_SHORT_FILENAME_LEN      3

			#define	SLIST_ENTRY(type)                               \
			struct {                                                \
			    struct type *sle_next;  /* next element */          \
			}

			#define	SLIST_HEAD(name, type)                          \
			struct name {                                           \
			    struct type *slh_first;	/* first element */         \
			}

			#define	TAILQ_HEAD(name, type)						\
			struct name {								\
				struct type *tqh_first;	/* first element */			\
				struct type **tqh_last;	/* addr of last next element */		\
			}

			#define	TAILQ_ENTRY(type)						\
			struct {								\
				struct type *tqe_next;	/* next element */			\
				struct type **tqe_prev;	/* address of previous next element */	\
			}

			struct nffs_hash_entry {
			    SLIST_ENTRY(nffs_hash_entry) nhe_next;
			    uint32_t nhe_id;        /* 0 - 0x7fffffff if inode; else if block. */
			    uint32_t nhe_flash_loc; /* Upper-byte = area idx; rest = area offset. */
			};

			SLIST_HEAD(nffs_inode_list, nffs_inode_entry);

			struct nffs_inode_entry {
			    struct nffs_hash_entry nie_hash_entry;
			    SLIST_ENTRY(nffs_inode_entry) nie_sibling_next;
			    union {
			        struct nffs_inode_list nie_child_list;           /* If directory */
			        struct nffs_hash_entry *nie_last_block_entry;    /* If file */
			        uint32_t nie_lastblock_id;
			    };
			    uint8_t nie_refcnt;
			    uint8_t nie_flags;
			    uint8_t nie_blkcnt;
			    uint8_t reserved8;
			};

			struct nffs_inode {
			    struct nffs_inode_entry *ni_inode_entry; /* Points to real inode entry. */
			    uint32_t ni_seq;                         /* Sequence number; greater
			                                                supersedes lesser. */
			    struct nffs_inode_entry *ni_parent;      /* Points to parent directory. */
			    uint8_t ni_filename_len;                 /* # chars in filename. */
			    uint8_t ni_filename[NFFS_SHORT_FILENAME_LEN]; /* First 3 bytes. */
			};

			struct nffs_file {
			    struct nffs_inode_entry *nf_inode_entry;
			    uint32_t nf_offset;
			    uint8_t nf_access_flags;
			};

			struct nffs_block {
			    struct nffs_hash_entry *nb_hash_entry;   /* Points to real block entry. */
			    uint32_t nb_seq;                         /* Sequence number; greater
			                                                supersedes lesser. */
			    struct nffs_inode_entry *nb_inode_entry; /* Owning inode. */
			    struct nffs_hash_entry *nb_prev;         /* Previous block in file. */
			    uint16_t nb_data_len;                    /* # of data bytes in block. */
			    uint16_t reserved16;
			};

			struct nffs_cache_block {
			    TAILQ_ENTRY(nffs_cache_block) ncb_link; /* Next / prev cached block. */
			    struct nffs_block ncb_block;            /* Full data block. */
			    uint32_t ncb_file_offset;               /* File offset of this block. */
			};

			TAILQ_HEAD(nffs_cache_block_list, nffs_cache_block);

			/** Represents a single cached file inode. */
			struct nffs_cache_inode {
			    TAILQ_ENTRY(nffs_cache_inode) nci_link;        /* Sorted; LRU at tail. */
			    struct nffs_inode nci_inode;                   /* Full inode. */
			    struct nffs_cache_block_list nci_block_list;   /* List of cached blocks. */
			    uint32_t nci_file_size;                        /* Total file size. */
			};

			struct nffs_dirent {
			    struct nffs_inode_entry *nde_inode_entry;
			};

			struct nffs_dir {
			    struct nffs_inode_entry *nd_parent_inode_entry;
			    struct nffs_dirent nd_dirent;
			};
			#endif
		</prologue>
		<func name="NEWTRON_init">
			<arg type="MASS_T *" name="mass" traceable="Y">Device containing Newtron filing system.</arg>
			<arg type="struct nffs_file *" name="files">Array of files.</arg>
			<arg type="size_t" name="n_files">Number of elements in <code>files[]</code>.</arg>
			<arg type="struct nffs_inode_entry *" name="inodes">Array of inodes.</arg>
			<arg type="size_t" name="n_inodes">Number of elements in <code>inodes[]</code>.</arg>
			<arg type="struct nffs_hash_entry *" name="blocks">Array of blocks.</arg>
			<arg type="size_t" name="n_blocks">Number of elements in <code>blocks[]</code>.</arg>
			<arg type="struct nffs_cache_inode *" name="cache_inodes">Array of cached inodes.</arg>
			<arg type="size_t" name="n_cache_inodes">Number of elements in <code>cache_inodes[]</code>.</arg>
			<arg type="struct nffs_cache_block *" name="cache_blocks">Array of cached blocks.</arg>
			<arg type="size_t" name="n_cache_blocks">Number of elemenst in <code>cache_blocks[]</code>.</arg>
			<arg type="struct nffs_dir *" name="dirs">Array of directories.</arg>
			<arg type="size_t" name="n_dirs">Number of elemenst in <code>dirs[]</code>.</arg>
			<return type="int32_t">
				<enum>
					<item val="Positive">Success.</item>
					<item val="Negative">Error.</item>
				</enum>
			</return>
			<limitations>
				<precondition>((mass != NULL) &amp;&amp; (files != NULL) &amp;&amp; (inodes != NULL) &amp;&amp; (blocks != NULL) &amp;&amp; (cache_inodes != NULL) &amp;&amp; (cache_blocks != NULL) &amp;&amp; (dirs != NULL))</precondition>
			</limitations>
			<description>
				Initialise a Newtron filing system on a MEOS mass storage device, using statically allocated memory. Replaces <code>nffs_init</code> in the Newtron initialisation sequence.
			</description>
		</func>
	</interface>
</module>

=== MIPS/meos/tmr/tmr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../doc/doc.xsl"?>
<module name="tmr" prefix="TMR" modtype="Functional">
	<description>Provides an abstraction of the underlying timer hardware.
		<par/>
		MEOS maintains a monotonically increasing jiffy clock which it
		uses for timers. This is a 32-bit free running, wrapping value.
		The length of a jiffy is implementation specific. This clock
		should be as accurate as possible.
	</description>
	<imports>irq</imports>
	<interface>
		<prologue>
		</prologue>
		<include lib="N">meos/config.h</include>
		<include lib="Y">stdint.h</include>
		<include lib="N">meos/irq/irq.h</include>
		<define vis="virtual"><c>TMR_PERFCOUNTERS</c>The number of performance
		counters available.</define>
		<func name="TMR_configPerfCount" vis="virtual">
			<arg name="counter">Counter index to retrieve.</arg>
			<arg name="event">Event to configure.</arg>
			<return type="void"/>
			Sets the platform specific event the performance counter counts.
			Please refer to your hardware documentation for a list of events.
			<par/>
			Beware that in some configurations, timers may be reset during
			initialisation. Please refer to the platform specific documentation.
			<par/>
			Note that this performs a naive configuration of the performance
			counter. For finer grained configuration, please use the appropriate
			native mechanism for configuring performance counters.
		</func>
		<func name="TMR_getMonotonic" vis="virtual">
			<voidargs/>
			<return type="uint64_t"/>
			<description>Returns the current count of the jiffy
			clock.
			</description>
		</func>
		<func name="TMR_getPerfCount" vis="virtual">
			<arg name="counter">Counter index to retrieve.</arg>
			<return type="uint64_t"/>
			Fetches the platform specific performance counter.
			<par/>
			Beware that in some configurations, timers may be reset during
			initialisation. Please refer to the platform specific documentation.
		</func>
		<func name="TMR_init">
			<voidargs/>
			<return type="void"/>
			<description>Implementation specific initialisation
			function. This <emph>must not</emph> be called by user
			code. This should not initialise cycle counters,
			<code>TMR_resetCycleCount</code> should perform this duty.
			</description>
		</func>
		<func name="TMR_resetCycleCount">
			<voidargs/>
			<return type="void"/>
			<description>Reset cycle counter.
				<par/>Typically this should initialise and zero performance
			counters to be used by <code>TMR_startCycleCount</code> and
			<code>TMR_stopCycleCount</code>.</description>
		</func>
		<func name="TMR_resetPerfCount" vis="virtual">
			<arg name="counter">Counter index to retrieve.</arg>
			<return type="uint64_t"/>
			Fetches and resets the platform specific performance counter.
			<par/>
			Beware that in some configurations, timers may be reset during
			initialisation. Please refer to the platform specific documentation.
		</func>
		<func name="TMR_route" vis="private">
			<arg type="IRQ_ISRFUNC_T" name="isrFunc">Pointer to the function which
			will handle the timer.</arg>
			<return type="void"/>
			<description>Registers a low level timer interrupt
			handler.
			<par/>
			This function is used by the kernel to implement timers.
			End users <emph>must not</emph> use this functions. This
			documentation is intended for implementors creating new
			ports <emph>only</emph>.</description>
		</func>
		<func name="TMR_set" vis="private">
			<arg type="uint32_t" name="abstime">Absolute monotonic time to trigger timer interrupt.</arg>
			<return type="void"/>
			<description>Triggers a timer interrupt when the jiffy timer
			reaches <code>abstime</code>.
			<par/>
			This function is used by the kernel to implement timers.
			End users <emph>must not</emph> use this function. This
			documentation is intended for implementors creating new
			ports <emph>only</emph>.</description>
		</func>
		<func name="TMR_setClockSpeed">
				<arg type="uint32_t" name="perus">Jiffies per microsecond.</arg>
				<return type="void"/>
				<limitations>
            <precondition>(perus != 0)</precondition>
            </limitations>
				<description>Set the number of jiffies per uSec.</description>
		</func>
		<func name="TMR_clockSpeed">
				<return type="uint32_t">Jiffies per uSec.</return>
				<description>Return the number of jiffies per uSec.</description>
		</func>
		<func name="TMR_startCycleCount" vis="virtual">
			<voidargs/>
			<return type="void"/>
			<description>Start counting cycles.</description>
		</func>
		<func name="TMR_stopCycleCount" vis="virtual">
			<voidargs/>
			<return type="uint32_t">Number of cycles since previous call to <code>TMR_startCycleCount</code>.</return>
			<limitations>
            <postcondition>(_RESULT != 0)</postcondition>
            </limitations>
			<description>Stops counting cycles and returns the number of cycles since the last call to <code>TMR_startCycleCount</code>. MEOS will attempt to compensate for overheads.</description>
		</func>
		<postinclude lib="N">meos/target/tmr.h</postinclude>
		<epilogue>
		</epilogue>
	</interface>
</module>

=== MIPS/meos/support/1/drivers/uart/uart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="uart" prefix="UART" modtype="Special">
	<description>Provides a framework for UART drivers.</description>
	<imports>kernel</imports>
	<imports>ring</imports>
	<interface>
		<include lib="Y">stdio.h</include>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<include lib="N">meos/rings/ring.h</include>
		<typedef vis="private"><c>struct UART_tag UART_T</c>(Incomplete) UART system object definition.</typedef>
		<typedef vis="virtual"><c>struct UART_T {<nl/>
		LST_LINK;<nl/>
		RING_T	tx;<nl/>
		RING_T	rx;<nl/>
		UART_CFGFUNC_T *config;<nl/>
		UART_ETEIFUNC_T *enableTXEmptyInt;<nl/>
		UART_READYFUNC_T *rFunc;<nl/>
		void * rPar;<nl/>
		}</c>UART type definition.
		<par/>
		<code>tx</code> will be filled with data by <code>UART_write</code>. Drivers should read and transmit data from this ring. Received data should be written to <code>rx</code> so it may be read by <code>UART_read</code>.
		<par/>
		<code>config</code> implements <code>UART_config</code>.
		<par/>
		<code>enableTXEmptyInt</code> is called when <code>tx</code> is full, so it may be drained by refilling the UART TX FIFO. Drivers must automatically disable this interrupt when it is no longer useful.
		<par/>
		<code>rFunc</code> and <code>rPar</code> are used to implement <code>UART_readyFunc</code>.
		</typedef>
		<typedef><c>int32_t UART_CFGFUNC_T(UART_T *uart, const char *mode)</c>Used to configure UART. See <code>UART_config</code> for details.</typedef>
		<typedef><c>void UART_ETEIFUNC_T(UART_T *uart)</c>Used to enable the TX buffer empty interrupt.</typedef>
		<typedef><c>void UART_READYFUNC_T(void *priv)</c>Called when there is data to be read. Registered with <code>UART_ready</code>.</typedef>
		<func name="UART_config" vis="virtual">
			<arg type="UART_T *" name="uart" tracable="Y">Pointer to UART system object.</arg>
			<arg type="const char *" name="config">Configuration string.</arg>
			<return type="int32_t">
				<enum>
					<item val="Non-zero">Reconfiguration failed.</item>
					<item val="0">Reconfiguration succeeded.</item>
				</enum>
			</return>
			<limitations>
				<precondition>((uart != NULL) &amp;&amp; (config != NULL))</precondition>
			</limitations>
			<description>Reconfigures a UART according to a configuration string.
			<par/>
			Configuration strings have the format &lt;baud&gt;&lt;parity&gt;[size][stop][flow], where <code>baud</code> is a numeric specifying the baudrate; <code>parity</code> is <emph>n</emph>, <emph>o</emph>, or <emph>e</emph> for none, odd, or even, respectively; <code>size</code> is the number of bits per character, <code>stop</code> is the number of stop bits, and <code>flow</code> is not present for none, or <emph>r</emph> for hardware flow control. Specific implementations may extend this syntax, as specified by their own documentation.
			</description>
		</func>
		<func name="UART_fopen">
			<arg type="UART_T *" name="uart" tracable="Y">Pointer to UART system object.</arg>
			<arg type="const char *" name="mode"><code>fopen</code> style mode string.</arg>
			<return type="FILE *">FILE pointer.</return>
			<limitations>
				<precondition>((uart != NULL) &amp;&amp; (mode != NULL))</precondition>
			</limitations>
			<description>Open a UART as a stdio compatible <code>FILE</code> object.</description>
		</func>
		<func name="UART_read">
			<arg type="void *" name="dummy">Unused.</arg>
			<arg type="void *" name="buffer">Buffer to read into.</arg>
			<arg type="int" name="size">Number of bytes to write per transaction.</arg>
			<arg type="int" name="n">Number of transactions.</arg>
			<arg type="void *" name="uart">UART to read data from.</arg>
			<return type="int">Number of transactions performed.</return>
			<limitations>
			<precondition>((buffer != NULL) &amp;&amp; (uart != NULL))</precondition>
			</limitations>
			<description>Read <code>size</code> multiplied by <code>n</code> bytes from <code>uart</code> to <code>buffer</code>.
			<par/>
			If <code>size</code> is 1, then this function will short read upon receiving a line ending. Additionally, other line endings will be converted to new lines.
			<par/>
			This function conforms to the <code>_mips_xfermem_fn</code> signature.
			</description>
		</func>
		<func name="UART_ready">
			<arg type="UART_T *" name="uart" traceable="Y">Pointer to UART.</arg>
			<return type="int32_t">
				<enum>
					<item val="Non-zero (TRUE)">Data available to read.</item>
					<item val="0 (FALSE)">Data not available.</item>
				</enum>
			</return>
			<limitations>
				<precondition>(uart != NULL)</precondition>
			</limitations>
			<description>Test for readable data.</description>
		</func>
		<func name="UART_readyFunc">
			<arg type="UART_T *" name="uart" traceable="Y">Pointer to UART.</arg>
			<arg type="UART_READYFUNC_T *" name="func">Pointer to callback function.</arg>
			<arg type="void *" name="par">Pointer to callback function parameter.</arg>
			<return type="void"/>
			<limitations>
				<precondition>(uart != NULL)</precondition>
			</limitations>
			<description>Provide a callback function to be invoked when the UART becomes ready to read.</description>
		</func>
		<func name="UART_write">
			<arg type="void *" name="dummy">Unused.</arg>
			<arg type="void *" name="buffer">Data to write.</arg>
			<arg type="int" name="size">Number of bytes to write per transaction.</arg>
			<arg type="int" name="n">Number of transactions.</arg>
			<arg type="void *" name="uart">UART to write data to.</arg>
			<return type="int">Number of transactions performed.</return>
			<limitations>
			<precondition>((buffer != NULL) &amp;&amp; (uart != NULL))</precondition>
			</limitations>
			<description>Write <code>size</code> multiplied by <code>n</code> bytes from <code>buffer</code> to <code>uart</code>.
			<par/>
			This function conforms to the <code>_mips_xfermem_fn</code> signature.
			</description>
		</func>
		<func name="UART_inject">
			<arg type="void *" name="dummy">Unused.</arg>
			<arg type="void *" name="buffer">Data to write.</arg>
			<arg type="int" name="size">Number of bytes to write per transaction.</arg>
			<arg type="int" name="n">Number of transactions.</arg>
			<arg type="void *" name="uart">UART to write data to.</arg>
			<return type="int">Number of transactions performed.</return>
			<limitations>
			<precondition>((buffer != NULL) &amp;&amp; (uart != NULL))</precondition>
			</limitations>
			<description>Write <code>size</code> multiplied by <code>n</code> bytes from <code>buffer</code> to the read queue of <code>uart</code>.
			<par/>
			This function conforms to the <code>_mips_xfermem_fn</code> signature.
			</description>
		</func>
		<func name="UART_extract">
			<arg type="void *" name="dummy">Unused.</arg>
			<arg type="void *" name="buffer">Buffer to read into.</arg>
			<arg type="int" name="size">Number of bytes to write per transaction.</arg>
			<arg type="int" name="n">Number of transactions.</arg>
			<arg type="void *" name="uart">UART to write data to.</arg>
			<return type="int">Number of transactions performed.</return>
			<limitations>
			<precondition>((buffer != NULL) &amp;&amp; (uart != NULL))</precondition>
			</limitations>
			<description>Read <code>size</code> multiplied by <code>n</code> bytes from the transmit queue of <code>uart</code> to <code>buffer</code>.
			<par/>
			This function conforms to the <code>_mips_xfermem_fn</code> signature.
			</description>
		</func>
		<epilogue>
/* complete the UART_T definition... */
struct UART_tag {
LST_LINK;
RING_T	tx;
RING_T	rx;
UART_CFGFUNC_T *config;
UART_ETEIFUNC_T *enableTXEmptyInt;
UART_READYFUNC_T *rFunc;
void * rPar;
};

#define UART_ready(U) !RING_empty(&amp;((UART_T*)(U))->rx)
#define UART_config(U, C) ((UART_T*)(U))->config((U), (C))
		</epilogue>
	</interface>
</module>

=== MIPS/meos/support/1/drivers/tcpsocket/tcpsocket.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="tcpsocket" prefix="TCPSOCKET" modtype="Special">
	<description>Implements a UART driver that communicates via a TCP socket.</description>
	<imports>kernel</imports>
	<imports>uart</imports>
	<interface>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<include lib="N">meos/uart/uart.h</include>
		<typedef>
			<c>struct TCPSOCKET_tag TCPSOCKET_T</c>(Incomplete) TCP socket UART system object definition.
		</typedef>
		<func name="TCPSOCKET_init">
			<arg type="TCPSOCKET_T *" name="uart" traceable="Y">Pointer to TCP socket UART system object.</arg>
			<arg type="uint8_t *" name="txBuf">Transmission byte buffer.</arg>
			<arg type="size_t" name="txLen">Number of bytes in <code>txBuf</code>.</arg>
			<arg type="uint8_t *" name="rxBuf">Receive byte buffer.</arg>
			<arg type="size_t" name="rxLen">Number of bytes in <code>rxBuf</code>.</arg>
			<arg type="KRN_TASK_T *" name="rxTask">Socket reader TCB.</arg>
			<arg type="uint32_t *" name="rxStack">Pointer to socket reader task workspace (stack).</arg>
			<arg type="size_t" name="rxStackSize">Size (in 32 bit words) of workspace.</arg>
			<return type="void"/>
			<limitations>
				<precondition>((uart != NULL) &amp;&amp; (txBuf != NULL) &amp;&amp; (txLen > 0) &amp;&amp; (rxBuf != NULL) &amp;&amp; (rxLen > 0))</precondition>
			</limitations>
			<description>Initialises the UART described by <code>uart</code> based on the provided configuration.
			</description>
		</func>
		<epilogue>

#include "lwip/api.h"

/* complete the TCP socket_T definition... */
struct TCPSOCKET_tag {
	UART_T	uart;
	const char *name;
	const char *interface;
	const uint32_t port;
	struct netconn *conn;
};
		</epilogue>
	</interface>
</module>

=== MIPS/meos/ipm/ipm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../doc/doc.xsl"?>
<module name="ipm" prefix="IPM" modtype="Functional">
	<description>Provides an abstraction of the underlying interprocessor
		messaging mechanism.</description>
	<imports>debug</imports>
	<imports>irq</imports>
	<imports>kernel</imports>
	<imports>lists</imports>
	<interface>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<func name="IPM_recv" vis="virpriv">
			<arg type="KRN_MSG_T *" name="message" traceable="Y">Message to send.</arg>
			<return type="void"/>
			<limitations>
			<precondition>(message != NULL)</precondition>
			</limitations>
			<description>Receive and process an inter-processor message from another core.</description>
		</func>
		<func name="IPM_send" vis="virpriv">
			<arg type="KRN_MSG_T *" name="message" traceable="Y">Message to send.</arg>
			<return type="void"/>
			<limitations>
			<precondition>(message != NULL)</precondition>
			</limitations>
			<description>Send an inter-processor message to another core.  This message should be accepted as quickly as possible, since this function should block and never fail.</description>
		</func>
		<func name="IPM_start" vis="virpriv">
			<voidargs/>
			<return type="void"/>
			<description>Implementation specific initialisation
			function. This <emph>must not</emph> be called by user
			code.
			<par/>
			Typically this will initialise a handler for incoming messages, which should deliver messages to <code>IPM_recv</code>.</description>
		</func>
		<epilogue>
#ifndef MEOS_NO_FUNCS
#ifdef CONFIG_FEATURE_IMPEXP
void _KRN_recv(KRN_MSG_T *message);
inline static void IPM_recv(KRN_MSG_T *message)
{
	_KRN_recv(message);
}
void IPM_send(KRN_MSG_T *message);
void IPM_start(void);
#else
void IPM_recv(KRN_MSG_T * message);
void IPM_send(KRN_MSG_T *message);
void IPM_start(void);
#endif
#endif
#ifdef CONFIG_DEBUG_IMPEXP_LOGGING
#include "meos/inttypes.h"
static inline void _IPM_impexpDebug(char *type, KRN_MSG_T * message)
{
	char sub[256], *subw = sub;
	const char *name;
	const char *commandNames[] = {
		"KRN_RESPONSE_ACK",
		"KRN_RESPONSE_NACK",
		"KRN_RESPONSE_NOTIFY",
		"KRN_COMMAND_SEMAPHORE_TEST",
		"KRN_COMMAND_SEMAPHORE_SET",
		"KRN_COMMAND_LOCK",
		"KRN_COMMAND_UNLOCK",
		"KRN_COMMAND_FLAGCLUSTER_TEST",
		"KRN_COMMAND_FLAGCLUSTER_SET",
		"KRN_COMMAND_FLAGCLUSTER_TOGGLE",
		"KRN_COMMAND_FLAGCLUSTER_CLEAR",
		"KRN_COMMAND_MAILBOX_GET",
		"KRN_COMMAND_MAILBOX_PUT",
		"KRN_COMMAND_POOL_TAKE",
		"KRN_COMMAND_POOL_RETURN",
		"KRN_COMMAND_SYNC",
		"KRN_COMMAND_WQ_QUEUE",
		"KRN_COMMAND_MEM_ANNOUNCE",
		"KRN_COMMAND_IMPORT_PROBE",
		"UPDATE IMPEXP DEBUG LIST!"
	};
	sub[0] = 0;
	if (message->subCmd &amp; KRN_SUBCOMMAND_OK)
		subw += sprintf(subw, "OK ");
	if (message->subCmd &amp; KRN_SUBCOMMAND_FAIL)
		subw += sprintf(subw, "FAIL ");
	if (message->subCmd &amp; KRN_SUBCOMMAND_WAIT)
		subw += sprintf(subw, "WAIT ");
	if (message->subCmd &amp; KRN_SUBCOMMAND_FLAGCLUSTER_ANY)
		subw += sprintf(subw, "ANY ");
	if (message->subCmd &amp; KRN_SUBCOMMAND_FLAGCLUSTER_CLEAR)
		subw += sprintf(subw, "CLEAR ");

	if (_KRN_current == NULL)
		name = "Unknown task";
	else if (_KRN_current->name != NULL)
		name = _KRN_current->name;
	else
		name = "Unnamed task";

	DBG_logF("%" PRIu32 " %s %s %d-&gt;%d\t%" PRId32 "&lt;=&gt;%" PRId32 "\t%" PRIu32 "\t%s\t%s\t%016" PRIx64 "\t%016" PRIx64 "\n",
		 KRN_proc(), name, type, message->from, message->to, message->cID,
		 message->sID, message->seq, commandNames[message->cmd], sub,
		 message->p64a, message->p64b);
}
#else
#define _IPM_impexpDebug(T, M)
#endif
		</epilogue>
	</interface>
</module>
