=== MIPS/meos/doc/module.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT module (description, imports*, interface)>
<!ATTLIST module
	modtype (Functional | System | Special) #REQUIRED
	name CDATA #REQUIRED
	prefix CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT enum (item)+>
<!ELEMENT item (#PCDATA | par | enum | emph | bold | code | nl)*>
<!ATTLIST item
	val CDATA #REQUIRED
>
<!ELEMENT par EMPTY>
<!ELEMENT imports (#PCDATA)>
<!ELEMENT prologue ANY>
<!ELEMENT epilogue ANY>
<!ELEMENT interface (prologue?, include*, define*, typedef*, var*, func*, postinclude*, epilogue?)>
<!ELEMENT include (#PCDATA)>
<!ATTLIST include
	lib (Y | N) #REQUIRED
>
<!ELEMENT postinclude (#PCDATA)>
<!ATTLIST postinclude
	lib (Y | N) #REQUIRED
>
<!ELEMENT define (#PCDATA | par | enum | emph | bold | code | c)*>
<!ATTLIST define
	vis (concrete | virtual) "concrete"
>
<!ELEMENT typedef (#PCDATA | par | enum | emph | bold | code | c)*>
<!ATTLIST typedef
	vis (public | private | anonymous | virtual | virpriv | viranon) #IMPLIED
>
<!ELEMENT var (#PCDATA | par | enum | emph | bold | code)*>
<!ATTLIST var
	type CDATA #REQUIRED
	decl CDATA #REQUIRED
>
<!ELEMENT func ((voidargs | (arg*, varargs?)), return, entry?, exit?, resources?, description, limitations?)>
<!ELEMENT entry (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT exit (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT resources (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT varargs EMPTY>
<!ELEMENT voidargs EMPTY>
<!ATTLIST func
	name CDATA #REQUIRED
	quals CDATA #IMPLIED
	vis (concrete | virtual | private | virpriv) "concrete"
	return (Y | N) "Y"
>
<!ELEMENT arg (#PCDATA | par | enum | emph | bold | code)*>
<!ATTLIST arg
	type CDATA #REQUIRED
	name CDATA #REQUIRED
	traceable (Y | N) "N"
>
<!ELEMENT return (#PCDATA | par | enum | emph | bold | code)*>
<!ATTLIST return
	type CDATA #REQUIRED
>
<!ELEMENT limitations (arglimit*, precondition*, postcondition*)>
<!ELEMENT c (#PCDATA | tab | nl | parahead | paratail)*>
<!ELEMENT emph (#PCDATA)>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT code (#PCDATA | tab | nl)*>
<!ELEMENT tab EMPTY>
<!ELEMENT nl EMPTY>
<!ELEMENT parahead EMPTY>
<!ELEMENT paratail EMPTY>
<!ELEMENT arglimit (#PCDATA | code | nl)*>
<!ATTLIST arglimit
	argname CDATA #REQUIRED
	min CDATA #IMPLIED
	max CDATA #IMPLIED
	mult CDATA #IMPLIED
	align (0 | 1 | 2 | 4 | 8 | pow2) "0"
	num (0 | Q63 | Q31 | Q23 | Q15 | Q7) "0"
>
<!ELEMENT precondition (#PCDATA)>
<!ELEMENT postcondition (#PCDATA)>

=== MIPS/meos/support/1/timisr/timisr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../doc/doc.xsl"?>
<module name="timisr" prefix="TIMISR" modtype="System">
	<description>Emulates the deprecated timer ISR mechanism.</description>
	<imports>kernel</imports>
	<interface>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<typedef><c>int32_t KRN_TIMERISRFUNC_T(void)</c> Timer ISR function.
		</typedef>
		<typedef vis="anonymous"><c>struct {<nl/>
			<tab/>DQ_LINK;<nl/>
			<parahead/>
			<tab/>KRN_TIMERISRFUNC_T *timisr;<nl/>
			<paratail/>
		} KRN_TIMERISR_T</c>Timer ISR descriptor.</typedef>
		<typedef><c>struct {<nl/>
			<parahead/>
			<tab/>DQ_T timerISRQ;<nl/>
			<tab/>KRN_TIMER_T timer;<nl/>
			<tab/>uint32_t rearm;<nl/>
			<paratail/>
		} TIMISR_T</c>TIMISR control structure.</typedef>
		<func name="KRN_activateTimerISR">
			<arg type="KRN_TIMERISR_T *" name="isr" traceable="Y">Pointer to timer
			ISR descriptor.</arg>
			<return type="void"/>
			<limitations>
            <precondition>(isr != NULL)</precondition>
            </limitations>
			<description>Activates a timer ISR. The ISR must first
			be initialised by <code>KRN_initTimerISR</code>.
			<par/>
			Timer ISRs are handled differently from generic ISRs
			(installed using <code>IRQ_route</code>). This is
			because multiple timer ISRs may be "daisy-chained" onto
			the timer tick interrupt.
			<par/>
			Once activated,	timer ISR functions will be executed in
			reverse order of activation on every scheduler clock
			tick until deactivated.
			<par/>
			A Timer ISR executes with interrupts disabled so it
			behaves like a repetitive, high priority, non
			pre-emptible task.
			<par/>
			The timer ISR's return value is used to influence the
			scheduler. If a timer ISR returns <code>non-zero</code>,
			then a scheduling event is guaranteed after the timer
			tick processing is complete. If the ISR returns
			<code>zero</code> then the scheduler is unaffected
			(although a scheduler event may still occur as a result
			of other timed processes).
			<par/>
			Take care to keep timer ISRs short and non-blocking.
			Most MEOS kernel functions are designed for use in
			background mode only - they must not be used inside ISRs.
			The descriptions of those functions which
			<emph>can</emph> be used in ISRs state this explicitly.
			</description>
		</func>
		<func name="KRN_deactivateTimerISR">
			<arg type="KRN_TIMERISR_T *" name="isr" traceable="Y">Pointer to timer
			ISR descriptor.</arg>
			<return type="void"/>
			<limitations>
            <precondition>(isr != NULL)</precondition>
            </limitations>
			<description>Deactivates a timer ISR. The ISR may be
			re-activated later if required. It need not be
			re-initialised.</description>
		</func>
		<func name="KRN_initTimerISR">
			<arg type="KRN_TIMERISR_T *" name="isr" traceable="Y">Pointer to timer
				ISR descriptor.</arg>
			<arg type="KRN_TIMERISRFUNC_T *" name="timerISRFunc">
				Pointer to timer ISR function.</arg>
			<return type="void"/>
			<limitations>
            <precondition>((isr != NULL) &amp;&amp; (timerISRFunc != NULL))</precondition>
            </limitations>
			<description>Creates a timer ISR object by associating a
			function with a timer ISR descriptor.
			<par/>
			Timer ISRs must be activated before they become
			effective.
			<par/>
			See the description of <code>KRN_activateTimerISR</code>
			for more details about timer ISR functions</description>
		</func>
		<func name = "TIMISR_init">
			<arg type="TIMISR_T *" name="timisr" traceable="Y">Pointer to TIMISR control structure.</arg>
			<arg type="uint32_t" name="rearm">Rearm interval in microseconds.</arg>
			<return type="void"/>
			<limitations>
			<precondition>((timisr != NULL) &amp;&amp; (rearm &gt; 0))</precondition>
			</limitations>
			<description>Initialise the timer ISR emulation system.</description>
		</func>
	</interface>
</module>

=== MIPS/meos/support/1/cpio/cpio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../doc/doc.xsl"?>
<module name="cpio" prefix="CPIO" modtype="Special">
	<description>Simple read only filesystem</description>
	<imports>fatfs</imports>
	<interface>
                <prologue>
#define CPIO_MAX_FILES (12)
#define CPIO_MAX_NAMESIZE (64)
#define CPIO_ASSUME_PDP (1)

#define CPIO_magic "070707"

#ifndef SEEK_SET
#define SEEK_SET 0
#endif
#ifndef SEEK_CUR
#define SEEK_CUR 1
#endif
#ifndef SEEK_END
#define SEEK_END 2
#endif

struct CPIO_stat;
		</prologue>
		<include lib="N">MEOS.h</include>
		<include lib="N">meos/mass/mass.h</include>
		<include lib="Y">stdint.h</include>
		<include lib="Y">stdint.h</include>
		<include lib="Y">errno.h</include>
		<include lib="Y">sys/types.h</include>

		<typedef>
			<c>struct CPIO_tag CPIO_T</c>CPIO object containing disk and open file information.
		</typedef>

		<typedef><c>struct {<nl/>
			<tab/>uint16_t dev;<nl/>
			<tab/>uint16_t ino;<nl/>
			<tab/>uint16_t mode;<nl/>
			<tab/>uint16_t uid;<nl/>
			<tab/>uint16_t gid;<nl/>
			<tab/>uint16_t nlink;<nl/>
			<tab/>uint16_t rdev;<nl/>
			<tab/>uint32_t mtime;<nl/>
			<tab/>uint16_t namesize;<nl/>
			<tab/>uint32_t filesize;<nl/>
		} CPIO_STAT_T</c>File information data, as used by <code>CPIO_stat</code>. Most information is only relevant to Unix systems, except <code>filesize</code>, the number of bytes in the file.</typedef>

		<func name="CPIO_init">
			<arg type="CPIO_T* const" name="c">CPIO object.</arg>
			<arg type="MASS_T* const" name="mass">MASS source object.</arg>
			<return type="int32_t">
				<enum>
					<item val="Positive">Success.</item>
					<item val="Negative">Error.</item>
				</enum>
			</return>
			<limitations>
				<precondition>((c != NULL) &amp;&amp; (mass != NULL))</precondition>
			</limitations>
			<description>Initialise a CPIO file system on mass storage device <code>mass</code>.
			</description>
		</func>

		<func name="CPIO_open">
			<arg type="CPIO_T* const" name="c">CPIO object.</arg>
			<arg type="const uint8_t* const" name="path">The path of the file to be opened.</arg>
			<return type="int32_t">
				<enum>
					<item val="Positive">Success.</item>
					<item val="-ENFILE"> Error - file table overflow.</item>
					<item val="-ENOEXIST"> Error - file not found.</item>
				</enum>
			</return>
			<limitations>
				<precondition>((c != NULL) &amp;&amp; (path != NULL))</precondition>
			</limitations>
			<description>Open the file with name <code>path</code>.
			</description>
		</func>

		<func name="CPIO_close">
			<arg type="CPIO_T* const" name="c">CPIO object.</arg>
			<arg type="const int" name="fd">The file descriptor of the file to be closed.</arg>
			<return type="void"/>
			<limitations>
				<precondition>(c != NULL)</precondition>
			</limitations>
			<description>Close the file with descriptor <code>fd</code>.
			</description>
		</func>

		<func name="CPIO_read">
			<arg type="CPIO_T* const" name="c">CPIO object.</arg>
			<arg type="const int" name="fd">The file descriptor of the file to be read.</arg>
			<arg type="uint8_t* const" name="buf">A pointer to the buffer to read into.</arg>
			<arg type="const size_t" name="count">The number of bytes to be read.</arg>
			<return type="ssize_t">
				<enum>
					<item val="Positive">Success - bytes read.</item>
					<item val="-EBADF">Error - bad file descriptor.</item>
					<item val="-EINVAL">Error - invalid arguments or file pointer out of range.</item>
				</enum>
			</return>
			<limitations>
				<precondition>((c != NULL) &amp;&amp; (buf != NULL))</precondition>
			</limitations>
			<description>Read <code>count</code> bytes from the file with descriptor <code>fd</code> into <code>buf</code>.
			</description>
		</func>

		<func name="CPIO_lseek">
			<arg type="CPIO_T* const" name="c">CPIO object.</arg>
			<arg type="const int" name="fd">The file descriptor of the file whose pointer is to be modified.</arg>
			<arg type="const off_t" name="offset">The offset from <code>whence</code> to move the file poiter.</arg>
			<arg type="const int" name="whence">The point with which <code>offset</code> will be summed to give the new file pointer. Can be one of: <code>SEEK_SET</code> indicates the begining of the file. <code>SEEK_CUR</code> the current file pointer position. <code>SEEK_END</code> the end of the file.</arg>
			<return type="off_t">
				<enum>
					<item val="Positive">Success - offset from start in bytes.</item>
					<item val="-EBADF">Error - bad file descriptor.</item>
				</enum>
			</return>
			<limitations>
				<precondition>(c != NULL)</precondition>
			</limitations>
			<description>Move the file pointer for <code>fd</code> to an <code>offset</code> from the point specified by <code>whence</code>.
			</description>
		</func>

		<func name="CPIO_tell">
			<arg type="CPIO_T* const" name="c">CPIO object.</arg>
			<arg type="const int" name="fd">The file descriptor of the file whose pointer is to be read.</arg>
			<return type="off_t">
				<enum>
					<item val="Positive">Success - offset from start in bytes.</item>
					<item val="-EBADF">Error - bad file descriptor.</item>
				</enum>
			</return>
			<limitations>
				<precondition>(c != NULL)</precondition>
			</limitations>
			<description>Get the current file pointer within <code>fd</code>.
			</description>
		</func>

		<func name="CPIO_stat">
			<arg type="CPIO_T* const" name="c">CPIO object.</arg>
			<arg type="const uint8_t* const" name="path">The path of the file to be evaluated.</arg>
			<arg type="CPIO_STAT_T* const" name="buf">The buffer to be overwritten with the file information.</arg>
			<return type="int32_t">
				<enum>
					<item val="Positive">Success.</item>
					<item val="-EBADF">Error - bad file descriptor.</item>
				</enum>
			</return>
			<limitations>
				<precondition>((c != NULL) &amp;&amp; (buf != NULL))</precondition>
			</limitations>
			<description>Get file information for <code>path</code>, and use it to fill <code>buf</code>.
			</description>
		</func>
		<epilogue>
typedef struct {
		uint32_t header;
		uint32_t data;
		uint32_t pointer;
		uint32_t next;
		uint32_t end;
} CPIO_FILE_T;

struct CPIO_tag {
	MASS_T *mass;
	int32_t (*gmr)(CPIO_T* const, uint8_t*, const uint32_t, const uint32_t);
	CPIO_FILE_T files[CPIO_MAX_FILES];
};
		</epilogue>
	</interface>
</module>

=== MIPS/meos/rings/ring.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../doc/doc.xsl"?>
<module name="rings" prefix="RING" modtype="Functional">
	<description>Provides general purpose functions for manipulating byte
	oriented ring buffers.<par/>
	All rings (<code>RING_T</code>) <emph>must</emph> be initialised before use.<par/>
	If <code>RING_INLINE</code> is defined, then this module can be in-lined rather than separately linked.</description>
	<imports>debug</imports>
	<interface>
		<prologue>
#ifdef RING_INLINE
#define RING_FQUALS inline static
#else
#ifdef RING_FQUALS
#undef RING_FQUALS
#endif
#define RING_FQUALS
#endif
	</prologue>
	<include lib="N">meos/config.h</include>
	<include lib="Y">stdint.h</include>
	<include lib="N">meos/debug/paranoia.h</include>
	<include lib="N">meos/kernel/krn.h</include>
		<typedef vis="anonymous"><c>struct {<nl/>
				<parahead/>
				<tab/>uint8_t *buffer;<nl/>
				<tab/>size_t size;<nl/>
				<tab/>size_t head;<nl/>
				<tab/>size_t tail;<nl/>
				<tab/>KRN_TASKQ_T rq;<nl/>
				<tab/>KRN_TASKQ_T wq;<nl/>
				<paratail/>
		}RING_T</c>
		Ring type.
		</typedef>
		<func name="RING_empty" quals="RING_FQUALS">
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<return type="int32_t">
				<enum>
					<item val="Non-zero (TRUE)">Ring is empty.</item>
					<item val="0 (FALSE)">Ring not empty.</item>
				</enum>
			</return>
			<limitations>
            <precondition>(ring != NULL)</precondition>
            </limitations>
			<description>Test for empty ring.</description>
		</func>
		<func name="RING_full" quals="RING_FQUALS">
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<return type="int32_t">
				<enum>
					<item val="Non-zero (TRUE)">Ring is full.</item>
					<item val="0 (FALSE)">Ring not full.</item>
				</enum>
			</return>
			<limitations>
            <precondition>(ring != NULL)</precondition>
            </limitations>
			<description>Test for full ring.</description>
		</func>
		<func name="RING_init" quals="RING_FQUALS">
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<arg type="uint8_t *" name="buffer" traceable="N">Pointer to buffer memory.</arg>
			<arg type="size_t" name="size" traceable="N">Pointer to size of buffer.</arg>
			<return type="void"/>
			<limitations>
            <precondition>((ring != NULL) &amp;&amp; (buffer != NULL) &amp;&amp; (size > 0))</precondition>
            </limitations>
			<description>Initialise a ring, using a memory of <code>size</code> bytes at <code>buffer</code>.</description>
		</func>
		<func name="RING_read" quals="RING_FQUALS">
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<arg type="uint8_t *" name="byte">Pointer to read byte into.</arg>
			<arg type="int32_t" name="timeout">Timeout (in scheduler clock ticks).</arg>
			<return type="int32_t">
				<enum>
					<item val="Non-zero (TRUE)">Byte read.</item>
					<item val="0 (FALSE)">Read failed.</item>
				</enum>
			</return>
			<limitations>
				<precondition>(ring != NULL)</precondition>
			</limitations>
			<description>
				Tries to read a byte from <code>ring</code> into <code>byte</code>.<par/>
				If <code>timeout</code> is negative, then the function
				will always succeed and return <code>non-zero</code>. If
				necessary, the caller will block until the there is a byte to
				read. If <code>timeout</code> is positive, then the caller will
				block for a maximum of <code>timeout</code> scheduler
				clock ticks before returning. A <code>zero</code> return
				indicates that the read could not succeed  before the
				timeout expired. In the special case of a zero
				<code>timeout</code> value, the function will return
				immediately without blocking: the return value will be
				<code>negative</code> unless the read can succeed
				immediately.</description>
		</func>
		<func name="RING_readBuffer" quals="RING_FQUALS">
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<arg type="uint8_t *" name="data">Pointer to read bytes into.</arg>
			<arg type="size_t" name="length">Number of bytes to read.</arg>
			<arg type="int32_t" name="timeout">Timeout (in scheduler clock ticks).</arg>
			<return type="int32_t">Number of bytes read.</return>
			<limitations>
				<precondition>((ring != NULL) &amp;&amp; (data != NULL))</precondition>
			</limitations>
			<description>
				Tries to read <code>length</code> bytes from <code>ring</code>
				into <code>data</code>. Will perform a partial read if
				insufficient data is available.<par/>
				If <code>timeout</code> is negative, then the function
				will always succeed and return non-zero. If
				necessary, the caller will block until the there is data to
				read. If <code>timeout</code> is positive, then the caller will
				block for a maximum of <code>timeout</code> scheduler
				clock ticks before returning. A <code>zero</code> return
				indicates that the read could not succeed  before the
				timeout expired. In the special case of a zero
				<code>timeout</code> value, the function will return
				immediately without blocking: the return value will be
				<code>negative</code> unless the read can succeed
				immediately.</description>
		</func>
				<func name="RING_size" vis="virtual">
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<return type="int32_t">Number of bytes in ring.</return>
			<limitations>
            <precondition>(ring != NULL)</precondition>
            </limitations>
			<description>Return the total number of bytes in <code>ring</code>.</description>
		</func>
		<func name="RING_space">
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<return type="int32_t">Number of empty bytes in ring.</return>
			<limitations>
				<precondition>(ring != NULL)</precondition>
			</limitations>
			<description>Return the number of empty bytes in <code>ring</code>.</description>
		</func>
		<func name="RING_used" >
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<return type="int32_t">Number of used bytes in ring.</return>
			<limitations>
				<precondition>(ring != NULL)</precondition>
			</limitations>
			<description>Return the number of used bytes in <code>ring</code>.</description>
		</func>
		<func name="RING_write" quals="RING_FQUALS">
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<arg type="uint8_t" name="byte">Byte to write.</arg>
			<arg type="int32_t" name="timeout">Timeout (in scheduler clock ticks).</arg>
			<return type="int32_t">
				<enum>
					<item val="Non-zero (TRUE)">Byte written.</item>
					<item val="0 (FALSE)">Write failed.</item>
				</enum>
			</return>
			<limitations>
				<precondition>(ring != NULL)</precondition>
			</limitations>
			<description>
				Tries to write a byte to <code>ring</code>.<par/>
				If <code>timeout</code> is negative, then the function
				will always succeed and return <code>non-zero</code>. If
				necessary, the caller will block until the there is a space to
				write into. If <code>timeout</code> is positive, then the caller
				will block for a maximum of <code>timeout</code> scheduler
				clock ticks before returning. A <code>zero</code> return
				indicates that the write could not succeed  before the
				timeout expired. In the special case of a zero
				<code>timeout</code> value, the function will return
				immediately without blocking: the return value will be
				<code>negative</code> unless the write can succeed
				immediately.</description>
		</func>
		<func name="RING_writeBuffer" quals="RING_FQUALS">
			<arg type="RING_T *" name="ring" traceable="Y">Pointer to ring.</arg>
			<arg type="uint8_t *" name="data">Bytes to write.</arg>
			<arg type="size_t" name="length">Number of bytes to write.</arg>
			<arg type="int32_t" name="timeout">Timeout (in scheduler clock ticks).</arg>
			<return type="int32_t">Number of bytes written.</return>
			<limitations>
				<precondition>(ring != NULL)</precondition>
			</limitations>
			<description>
				Tries to write <code>length</code> bytes to <code>ring</code>. Will perform a partial write if
				insufficient space is available.<par/>
				If <code>timeout</code> is negative, then the function
				will always succeed and return <code>non-zero</code>. If
				necessary, the caller will block until the there is a space to
				write into. If <code>timeout</code> is positive, then the caller
				will block for a maximum of <code>timeout</code> scheduler
				clock ticks before returning. A <code>zero</code> return
				indicates that the write could not succeed  before the
				timeout expired. In the special case of a zero
				<code>timeout</code> value, the function will return
				immediately without blocking: the return value will be
				<code>negative</code> unless the write can succeed
				immediately.</description>
		</func>
		<epilogue>
#define RING_size(R) ((R)->size)

#ifndef MEOS_NO_FUNCS
#ifdef RING_INLINE
#define RING_CINCLUDE
#include "meos/rings/ring.c"
#endif
#endif
</epilogue>
	</interface>
</module>

=== MIPS/meos/ctx/ctx.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../doc/doc.xsl"?>
<module name="ctx" prefix="CTX" modtype="Functional">
	<description>Provides an abstraction of the underlying CPU context.
	<par/>
	This functionality is used by the kernel to implement tasks. It contains no
	end user functionality, and you <emph>must not</emph> directly use its
	facilities.
	</description>
	<imports>kernel</imports>
	<interface>
		<include lib="N">meos/config.h</include>
		<include lib="Y">stdint.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<func name="CTX_attachBGTask" vis="private">
			<arg type="KRN_TASK_T *" name="task" traceable="Y">Background TCB.</arg>
			<return type="void"/>
			<limitations>
			<precondition>(task != NULL)</precondition>
			</limitations>
			<description>Attaches the running thread to the
			specified TCB, filling in as many fields as possible.
			See the description of <code>CTX_startTask</code> for
			more details about TCB fields.</description>
		</func>
		<func name="CTX_init" vis="private">
			<voidargs/>
			<return type="void"/>
			<description>Implementation specific initialisation
			function. This <emph>must not</emph> be called by user
			code.
			<par/>
			Typically this should attach <code>
			_KRN_schedulerISR</code> to the platform specific
			invocation mechanism.</description>
		</func>
		<func name="CTX_remove" vis="virpriv">
			<arg type="KRN_TASK_T *" name="task" traceable="Y">TCB of task to
			remove</arg>
			<return type="void"/>
			<limitations>
			<precondition>(task != NULL)</precondition>
			</limitations>
			<description>Removes the specified context from
			circulation after it has been removed from
			scheduling. Typically this will be a no-op.
			</description>
		</func>
		<func name="CTX_sleep" vis="private">
			<voidargs/>
			<return type="void"/>
			<description>Enters low power sleep, pending
			interruption.
			<par/>
			This marks the end of an interrupt handler, and may not
			return, depending on implementation. As such it should
			always be followed by a <code>return</code> statement.
		</description>
		</func>
		<func name="CTX_startTask" vis="private">
			<arg type="KRN_TASK_T *" name="task" traceable="Y">TCB for new task.
			</arg>
			<arg type="uintptr_t" name="workspace">Start of stack
			memory for task.</arg>
			<arg type="size_t" name="wssize">Length of stack memory
			in 32-bit words.</arg>
			<arg type="KRN_TASKFUNC_T *" name="taskfunc">Function
			to execute in new task.</arg>
			<return type="void"/>
			<limitations>
			<precondition>((task != NULL) &amp;&amp; (workspace != 0) &amp;&amp; (wssize != 0) &amp;&amp; (taskfunc != NULL))</precondition>
			</limitations>
			<description>Creates the neccessary context to execute
			<code>task_func</code> on the specified stack, and
			attaches the appropriate context switching functions to
			allow it to be switched.
			</description>
		</func>
		<func name="CTX_verifyTask" vis="private">
			<arg type="KRN_TASK_T *" name="task" traceable="Y">TCB of task to
			check.</arg>
			<return type="void"/>
			<limitations>
			<precondition>(task != NULL)</precondition>
			</limitations>
			<description>Verifies that the specified task has not
			exceeded its constraints, e.g. stack limits.
			</description>
		</func>
		<func name="CTX_verifySelf" vis="private">
			<arg type="KRN_TASK_T *" name="task" traceable="Y">TCB of task to
			check.</arg>
			<return type="void"/>
			<limitations>
			<precondition>(task != NULL)</precondition>
			</limitations>
			<description>Verifies that the executing code has not
			exceeded the constraints of the specified task, e.g. stack limits.
			</description>
		</func>
		<postinclude lib="N">meos/target/ctx.h</postinclude>
	</interface>
</module>

=== MIPS/meos/support/1/drivers/mrf24g/mrf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="mrf" prefix="MRF" modtype="Special">
	<description>MRF24WG driver</description>
	<interface>
		<include lib="N">MEOS.h</include>
		<include lib="N">meos/mrf24g/mrf_connection.h</include>
		<include lib="N">meos/mrf24g/mrf_raw.h</include>
		<include lib="N">meos/mrf24g/mrf_const.h</include>
    <typedef><c>void (*MRF_IPCB_T)(void *arg) </c>Input callback type</typedef>
		<func name="MRF_idle">
			<return type="int"/>
			<description>Checks the interrupt pin and handles input.
			</description>
		</func>
    <func name="MRF_get_interrupt">
      <arg type="enum MRF_interrupt_types" name="type" traceable="Y">Interrupt to read</arg>
      <return type="int"/>
      <description>Reads the interrupt registers and returns 1 if the specified
        interrupt is set, 0 otherwise. Also clears the bit in the register.
      </description>
    </func>
    <func name="MRF_rx_read">
      <arg type="uint8_t* const" name="buf" traceable="Y">Buffer to read into</arg>
      <arg type="const size_t" name="offset" traceable="Y">Offset into the RAW buffer</arg>
      <arg type="const size_t" name="size" traceable="Y">Size of read</arg>
      <return type="int"/>
      <description>Performs a read from the RAW data rx into the buffer <code>buf</code>.
      </description>
    </func>
    <func name="MRF_tx_write">
      <arg type="const uint8_t* const" name="buf" traceable="Y">Buffer to read from</arg>
      <arg type="const size_t" name="offset" traceable="Y">Offset into the RAW buffer</arg>
      <arg type="const size_t" name="size" traceable="Y">Size of write</arg>
      <return type="int"/>
      <description>Performs a write into the RAW data rx from the buffer <code>buf</code>.
      </description>
    </func>
    <func name="MRF_init">
      <arg type="MRF_IPCB_T" name="_input_cb" traceable="Y">Input_callback, called from the idle function</arg>
      <arg type="void *" name="_input_cb_arg" traceable="Y">Argument passed to the input callback</arg>
      <return type="int"/>
      <description>Initialises the MRF module
      </description>
    </func>
    </interface>
</module>

=== MIPS/meos/support/1/drivers/lan9211/lan9211.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="lan9211" prefix="LAN9211" modtype="Special">
	<description>LAN9211 LWIP driver</description>
	<imports>kernel</imports>
	<imports>lwip</imports>
	<interface>
		<include lib="Y">stdio.h</include>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<include lib="N">lwip/netif.h</include>
		<typedef vis="private"><c>struct LAN9211_tag LAN9211_T</c>(Incomplete) LAN9211 system object definition.</typedef>
		<func name="LAN9211_dtInit">
			<arg type="LAN9211_T *" name="lan9211" traceable="Y">Pointer to LAN9211 system object.</arg>
			<arg type="IRQ_DESC_T *" name="irq">IRQ descriptor for specified LAN9211.</arg>
			<return type="void"/>
			<limitations>
				<precondition>((lan9211 != NULL) &amp;&amp; (irq != NULL))</precondition>
			</limitations>
			<description>Initialises the LAN9211 described by <code>lan9211</code> based on the provided configuration.
			</description>
		</func>
		<epilogue>
/* complete the LAN9211_T definition... */
struct LAN9211_tag {
	uintptr_t	pAddr;
	volatile uint32_t*	regs;
	uint8_t backupMac[6];
	struct netif netif;
};
		</epilogue>
	</interface>
</module>
