=== MIPS/meos/doc/module.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT module (description, imports*, interface)>
<!ATTLIST module
	modtype (Functional | System | Special) #REQUIRED
	name CDATA #REQUIRED
	prefix CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT enum (item)+>
<!ELEMENT item (#PCDATA | par | enum | emph | bold | code | nl)*>
<!ATTLIST item
	val CDATA #REQUIRED
>
<!ELEMENT par EMPTY>
<!ELEMENT imports (#PCDATA)>
<!ELEMENT prologue ANY>
<!ELEMENT epilogue ANY>
<!ELEMENT interface (prologue?, include*, define*, typedef*, var*, func*, postinclude*, epilogue?)>
<!ELEMENT include (#PCDATA)>
<!ATTLIST include
	lib (Y | N) #REQUIRED
>
<!ELEMENT postinclude (#PCDATA)>
<!ATTLIST postinclude
	lib (Y | N) #REQUIRED
>
<!ELEMENT define (#PCDATA | par | enum | emph | bold | code | c)*>
<!ATTLIST define
	vis (concrete | virtual) "concrete"
>
<!ELEMENT typedef (#PCDATA | par | enum | emph | bold | code | c)*>
<!ATTLIST typedef
	vis (public | private | anonymous | virtual | virpriv | viranon) #IMPLIED
>
<!ELEMENT var (#PCDATA | par | enum | emph | bold | code)*>
<!ATTLIST var
	type CDATA #REQUIRED
	decl CDATA #REQUIRED
>
<!ELEMENT func ((voidargs | (arg*, varargs?)), return, entry?, exit?, resources?, description, limitations?)>
<!ELEMENT entry (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT exit (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT resources (#PCDATA | par | enum | emph | bold | code)*>
<!ELEMENT varargs EMPTY>
<!ELEMENT voidargs EMPTY>
<!ATTLIST func
	name CDATA #REQUIRED
	quals CDATA #IMPLIED
	vis (concrete | virtual | private | virpriv) "concrete"
	return (Y | N) "Y"
>
<!ELEMENT arg (#PCDATA | par | enum | emph | bold | code)*>
<!ATTLIST arg
	type CDATA #REQUIRED
	name CDATA #REQUIRED
	traceable (Y | N) "N"
>
<!ELEMENT return (#PCDATA | par | enum | emph | bold | code)*>
<!ATTLIST return
	type CDATA #REQUIRED
>
<!ELEMENT limitations (arglimit*, precondition*, postcondition*)>
<!ELEMENT c (#PCDATA | tab | nl | parahead | paratail)*>
<!ELEMENT emph (#PCDATA)>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT code (#PCDATA | tab | nl)*>
<!ELEMENT tab EMPTY>
<!ELEMENT nl EMPTY>
<!ELEMENT parahead EMPTY>
<!ELEMENT paratail EMPTY>
<!ELEMENT arglimit (#PCDATA | code | nl)*>
<!ATTLIST arglimit
	argname CDATA #REQUIRED
	min CDATA #IMPLIED
	max CDATA #IMPLIED
	mult CDATA #IMPLIED
	align (0 | 1 | 2 | 4 | 8 | pow2) "0"
	num (0 | Q63 | Q31 | Q23 | Q15 | Q7) "0"
>
<!ELEMENT precondition (#PCDATA)>
<!ELEMENT postcondition (#PCDATA)>

=== MIPS/meos/support/1/librproc/res.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../doc/doc.xsl"?>
<module name="res" prefix="RES" modtype="Functional">
	<description>Provides structures for defining ELF resource_table sections.</description>
	<interface>
		<prologue>
		</prologue>
		<include lib="N">meos/config.h</include>
		<include lib="Y">stdint.h</include>
		<typedef><c>struct {<nl/>
			<tab/>uint32_t version;<nl/>
			<tab/>uint32_t numEntries;<nl/>
			<tab/>uint32_t reserved[2];<nl/>
			<tab/>uint32_t offset[0];<nl/>
			} __attribute__((packed)) RES_TABLE_T</c>Resource table header.</typedef>
		<typedef><c>enum {<nl/>
			<tab/>RES_TYPE_CARVEOUT = 0,<nl/>
			<tab/>RES_TYPE_DEVMEM = 1,<nl/>
			<tab/>RES_TYPE_TRACE = 2,<nl/>
			<tab/>RES_TYPE_VDEV = 3,<nl/>
			<tab/>RES_TYPE_IPI = 4,<nl/>
			<tab/>RES_TYPE_LAST = 5<nl/>
			} RES_TYPE_T</c>Constants used for declaring resource table entries.</typedef>
		<typedef><c>struct {<nl/>
			<tab/>uint32_t type;<nl/>
			<tab/>uint8_t data[0];<nl/>
			} __attribute__((packed)) RES_ENTRY_T</c>Resource table entry.</typedef>
		<typedef><c>struct {<nl/>
			<tab/>uint32_t myAddress;<nl/>
			<tab/>uint32_t phyAddress;<nl/>
			<tab/>uint32_t length;<nl/>
			<tab/>uint32_t flags;<nl/>
			<tab/>uint32_t reserved;<nl/>
			<tab/>char name[32];<nl/>
			} __attribute__((packed)) RES_ENTRY_CARVEOUT_T</c>Resource table carve-out entry.</typedef>
		<typedef><c>struct {<nl/>
			<tab/>uint32_t myAddress;<nl/>
			<tab/>uint32_t phyAddress;<nl/>
			<tab/>uint32_t length;<nl/>
			<tab/>uint32_t flags;<nl/>
			<tab/>uint32_t reserved;<nl/>
			<tab/>char name[32];<nl/>
			} __attribute__((packed)) RES_ENTRY_DEVMEM_T</c>Resource table device memory entry.</typedef>
		<typedef><c>struct {<nl/>
			<tab/>uint32_t myAddress;<nl/>
			<tab/>uint32_t length;<nl/>
			<tab/>uint32_t reserved;<nl/>
			<tab/>char name[32];<nl/>
			} __attribute__((packed)) RES_ENTRY_TRACE_T</c>Resource table trace buffer entry.</typedef>
		<typedef><c>struct {<nl/>
			<tab/>uint32_t myAddress;<nl/>
			<tab/>uint32_t pageAlign;<nl/>
			<tab/>uint32_t numBuffers;<nl/>
			<tab/>uint32_t notifyId;<nl/>
			<tab/>uint32_t reserved;<nl/>
			} __attribute__((packed)) RES_ENTRY_RING_T</c>Resource table ring buffer entry.</typedef>
		<typedef><c>enum {<nl/>
			<tab/>RES_DEVICE_NET = 1,<nl/>
			<tab/>RES_DEVICE_BLOCK = 2,<nl/>
			<tab/>RES_DEVICE_CONSOLE = 3,<nl/>
			<tab/>RES_DEVICE_RNG = 4,<nl/>
			<tab/>RES_DEVICE_BALLOON = 5,<nl/>
			<tab/>RES_DEVICE_RPMSG = 7,<nl/>
			<tab/>RES_DEVICE_SCSI = 8,<nl/>
			<tab/>RES_DEVICE_9P = 9,<nl/>
			<tab/>RES_DEVICE_RPROC_SERIAL = 11,<nl/>
			<tab/>RES_DEVICE_CAIF = 12<nl/>
			} RES_DEVICE_T</c>Constants used for declaring resource table device entries.</typedef>
		<typedef><c>struct {<nl/>
			<tab/>uint32_t type;<nl/>
			<tab/>uint32_t notifyId;<nl/>
			<tab/>uint32_t devFeatures;<nl/>
			<tab/>uint32_t linuxFeatures;<nl/>
			<tab/>uint32_t configLength;<nl/>
			<tab/>uint8_t status;<nl/>
			<tab/>uint8_t numRings;<nl/>
			<tab/>uint8_t reserved[2];<nl/>
			<tab/>RES_ENTRY_RING_T rings[0];<nl/>
			} __attribute__((packed)) RES_ENTRY_DEVICE_T</c>Resource table virtual device entry.</typedef>
		<typedef><c>struct {<nl/>
			<tab/>uint16_t columns;<nl/>
			<tab/>uint16_t rows;<nl/>
			<tab/>uint32_t maximumPorts;<nl/>
			<tab/>uint32_t emergencyOut;<nl/>
			} __attribute__((packed)) RES_ENTRY_RPS_CONFIG_T</c>Resource table virtual comms serial port device entry.</typedef>
		<typedef><c>enum {<nl/>
			<tab/>RES_RPS_DEV_READY = 0,<nl/>
			<tab/>RES_RPS_PORT_ADD = 1,<nl/>
			<tab/>RES_RPS_PORT_REMOVE = 2,<nl/>
			<tab/>RES_RPS_PORT_READY = 3,<nl/>
			<tab/>RES_RPS_CONSOLE_PORT = 4,<nl/>
			<tab/>RES_RPS_RESIZE = 5,<nl/>
			<tab/>RES_RPS_PORT_OPEN = 6,<nl/>
			<tab/>RES_RPS_PORT_NAME = 7<nl/>
			} RES_RPS_COMMAND_T</c>Constants used for controlling virtual comms serial port.</typedef>
		<typedef><c>struct {<nl/>
			<tab/>uint32_t id;<nl/>
			<tab/>uint16_t event;<nl/>
			<tab/>uint16_t value;<nl/>
			} __attribute__((packed)) RES_ENTRY_RPS_CONTROL_T</c>Virtual comms serial port control message.</typedef>
		<typedef><c>struct {<nl/>
			<tab/>uint32_t direction;<nl/>
			<tab/>uint32_t hwirq;<nl/>
			} __attribute__((packed)) RES_ENTRY_IPI_T</c>Resource table interrupt entry.</typedef>
		<typedef><c>enum {<nl/>
			<tab/>RES_IPI_TO_FW = 0,<nl/>
			<tab/>RES_IPI_FROM_FW = 1<nl/>
			} RES_IPI_TYPE_T</c>Constants used for controlling interrupt communication.</typedef>
		<epilogue>
		</epilogue>
	</interface>
</module>

=== MIPS/meos/support/1/lopri/lopri.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../doc/doc.xsl"?>
<module name="lopri" prefix="LOPRI" modtype="Special">
	<description>Implements a common lowest priorty work queue. Use <code>KRN_queueWQ</code> to queue jobs on <code>LOPRI</code>.</description>
	<imports>kernel</imports>
	<interface>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<typedef>
			<c>struct LOPRI_tag LOPRI_T</c>LOPRI system object.
		</typedef>
		<var type="KRN_WQ_T *" decl="LOPRI">
			LOPRI queue. Use this when queuing low priority jobs.
		</var>
		<func name="LOPRI_init">
			<arg type="LOPRI_T *" name="lp" traceable="Y">Pointer to LOPRI system object.</arg>
			<return type="void"/>
			<limitations>
				<precondition>(lopri != NULL)</precondition>
			</limitations>
			<description>Start the lowest priority common work queue.
			</description>
		</func>
		<epilogue>
/* complete the LOPRI_T definition... */
struct  LOPRI_tag{<nl/>
		<tab/>KRN_WQ_T wq;<nl/>
		<tab/>KRN_TASK_T tasks[1];<nl/>
		<tab/>uint32_t stacks[CONFIG_LOPRI_STACKSIZE];<nl/>
		<tab/>KRN_JOB_T jobs[CONFIG_LOPRI_JOBS];<nl/>
		};<nl/>
		</epilogue>
	</interface>
</module>

=== MIPS/meos/support/1/drivers/fdc/fdc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="fdc" prefix="FDC" modtype="Special">
	<description>Implements an FDC UART driver.</description>
	<imports>kernel</imports>
	<imports>uart</imports>
	<interface>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<include lib="N">meos/uart/uart.h</include>
		<typedef>
			<c>struct FDC_tag FDC_T</c>(Incomplete) FDC system object definition.
		</typedef>
		<func name="FDC_init">
			<arg type="FDC_T *" name="fdc" traceable="Y">Pointer to FDC system object.</arg>
			<arg type="uint8_t *" name="txBuf">Transmission byte buffer.</arg>
			<arg type="size_t" name="txLen">Number of bytes in <code>txBuf</code>.</arg>
			<arg type="uint8_t *" name="rxBuf">Receive byte buffer.</arg>
			<arg type="size_t" name="rxLen">Number of bytes in <code>rxBuf</code>.</arg>
			<return type="void"/>
			<limitations>
				<precondition>((fdc != NULL) &amp;&amp; (txBuf != NULL) &amp;&amp; (txLen > 0) &amp;&amp; (rxBuf != NULL) &amp;&amp; (rxLen > 0))</precondition>
			</limitations>
			<description>Initialises the FDC described by <code>fdc</code> based on the provided configuration.
			</description>
		</func>
		<epilogue>
/* complete the FDC_T definition... */
struct FDC_tag {
	UART_T	uart;
	uint32_t channel;
};
		</epilogue>
	</interface>
</module>

=== MIPS/meos/support/1/tftp/tftp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../doc/doc.xsl"?>
<module name="tftp" prefix="TFTP" modtype="Special">
	<description>Trivial File Transfer Protocol.</description>
	<imports>kernel</imports>
	<imports>lwip</imports>
	<interface>
		<typedef>
			<c>struct TFTP_tag TFTP_T</c>TFTP connection object.
		</typedef>
		<func name="TFTP_init">
			<arg type="TFTP_T *" name="tftp">TFTP connection object.</arg>
			<arg type="const char *" name="host">Host name to connect to.</arg>
			<arg type="const char *" name="filename">File to download</arg>
			<return type="void"/>
			<limitations>
				<precondition>((tftp != NULL) &amp;&amp; (host != NULL) &amp;&amp; (filename != NULL))</precondition>
			</limitations>
			<description>Initialise a TFTP connection object. Connection does not occur until transfers are performed with <code>TFTP_read()</code>.
			</description>
		</func>
		<func name="TFTP_read">
			<arg type="void *" name="offset">The number of bytes into the stream, cast to a void pointer.</arg>
			<arg type="void *" name="recvBuffer">The buffer to read into.</arg>
			<arg type="int" name="size">Transfer size.</arg>
			<arg type="int" name="n">Number of transfers.</arg>
			<arg type="void *" name="vtftp"><code>TFTP_T</code> object, cast to a void pointer.</arg>
			<return type="int">Number of bytes transferred, or negative on error</return>
			<description>Download <code>size*n</code> bytes of data as specified from <code>vtftp</code>. Uses the MIPS HAL <code>_mips_xfermem_fn </code> interface.</description>
		</func>
		<epilogue>
		struct TFTP_tag {
			const char* host;
			const char* filename;
			uint32_t port;
		};
		</epilogue>
	</interface>
</module>

=== MIPS/meos/support/1/drivers/mrf24g/mrf_connection.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="MRF_connection" prefix="MRF_CONNECTION" modtype="Special">
	<description>MRF24WG driver connection functions</description>
	<interface>
    <include lib="Y">stdint.h</include>
    <prologue>
		#define MRF_BSSID_LENGTH (6)
		#define MRF_MAX_SSID_LENGTH (32)
		#define MRF_MAX_NUM_RATES (8)
    </prologue>
    <typedef><c>struct {<nl/>
		    <tab/>uint8_t version;<nl/>
		    <tab/>uint8_t patch;<nl/>
    } MRF_VINFO_T</c>
    Version information.
    </typedef>

	<typedef><c>struct {<nl/>
		<tab/>uint8_t bssid[MRF_BSSID_LENGTH];<nl/>
		<tab/>uint8_t ssid[MRF_MAX_SSID_LENGTH];<nl/>
		<tab/>uint8_t apConfig;<nl/>
		<tab/>uint8_t reserved;<nl/>
		<tab/>uint16_t beaconPeriod;<nl/>
		<tab/>uint16_t atimWindow;<nl/>
		<tab/>uint8_t basicRateSet[MRF_MAX_NUM_RATES];<nl/>
		<tab/>uint8_t rssi;<nl/>
		<tab/>uint8_t numRates;<nl/>
		<tab/>uint8_t DtimPeriod;<nl/>
		<tab/>uint8_t bssType;<nl/>
		<tab/>uint8_t channel;<nl/>
		<tab/>uint8_t ssidLen;<nl/>
	} MRF_SCAN_RESULT_T</c>
	Scan result
    </typedef>
	<func name="MRF_pctxCreate" vis="private">
      <return type="int"/>
      <description>
      </description>
    </func>
    <func name="MRF_ssidSet">
      <arg type="const uint8_t* const" name="ssid" traceable="Y">Buffer containing the SSID</arg>
      <arg type="const uint8_t" name="length" traceable="Y">length of the SSID (nulls are valid in SSIDs so a length must be provided)</arg>
      <return type="int"/>
      <description>Sets the SSID.
      </description>
    </func>
    <func name="MRF_ssidGet">
      <arg type="uint8_t* const" name="ssid" traceable="Y">Buffer long enough for the SSID (MAX 32 chars)</arg>
      <return type="int"/>
      <description>Gets the SSID.
      </description>
    </func>
    <func name="MRF_bssidSet">
      <arg type="const uint8_t* const" name="bssid" traceable="Y">Buffer containing the BSSID</arg>
      <return type="int"/>
      <description>Sets the BSSID.
      </description>
    </func>
    <func name="MRF_networkTypeSet">
      <arg type="const uint8_t" name="network_type" traceable="Y">Network type,
        either MRF_NETWORK_TYPE_INFRASTRUCTURE, MRF_NETWORK_TYPE_ADHOC, or
        MRF_NETWORK_TYPE_SOFT_AP</arg>
      <return type="int"/>
      <description>Sets the network type to infrastructure, ad-hoc or soft AP.
      </description>
    </func>
    <func name="MRF_networkTypeGet">
      <arg type="uint8_t*" name="network_type" traceable="Y">Network type,
        either MRF_NETWORK_TYPE_INFRASTRUCTURE, MRF_NETWORK_TYPE_ADHOC, or
        MRF_NETWORK_TYPE_SOFT_AP</arg>
      <return type="int"/>
      <description>Gets the network type the module is set to.
      </description>
    </func>
    <func name="MRF_securityOpenSet">
      <return type="int"/>
      <description>Sets the security method to open.
      </description>
    </func>
    <func name="MRF_scanTypeSet">
      <arg type="const uint8_t" name="type" traceable="Y">Scan type, either
        MRF_ACTIVE_SCAN or MRF_PASSIVE_SCAN</arg>
      <return type="int"/>
      <description>Sets whether the module will scan passively or actively.
      </description>
    </func>
    <func name="MRF_scanCountSet">
      <arg type="const uint8_t" name="count" traceable="Y">Scan count</arg>
      <return type="int"/>
      <description>Sets the scan count.
      </description>
    </func>
    <func name="MRF_scanMinChannelTimeSet">
      <arg type="const uint16_t" name="tim" traceable="Y">Min scan time</arg>
      <return type="int"/>
      <description>Sets the minimum channel scan time.
      </description>
    </func>
    <func name="MRF_scanMaxChannelTimeSet">
      <arg type="const uint16_t" name="tim" traceable="Y">Max scan time</arg>
      <return type="int"/>
      <description>Sets the maximum channel scan time.
      </description>
    </func>
    <func name="MRF_scanProbeDelaySet">
      <arg type="const uint16_t" name="tim" traceable="Y">The scan probe delay time</arg>
      <return type="int"/>
      <description>Sets the scan probe delay time.
      </description>
    </func>
	<func name="MRF_scan">
	  <return type="int"/>
	  <description>Starts a scan.
	  </description>
	</func>
	<func name="MRF_scanGetResultsCount">
	  <return type="uint16_t"/>
	  <description>Returns the number of scan results available to read, always 0 while a scan is in progress.
	  </description>
	</func>
	<func name="MRF_scanGetResult">
	  <arg type="MRF_SCAN_RESULT_T* const" name="result" traceable="Y">Buffer in which to place the result</arg>
	  <arg type="const uint8_t" name="index" traceable="Y">index of the result</arg>
	  <return type="int"/>
	  <description>Overwrites result with the scan result at index.
	  </description>
	</func>
    <func name="MRF_rssiSet">
      <arg type="const uint8_t" name="rssi" traceable="Y">RSSI</arg>
      <return type="int"/>
      <description>Sets the RSSI.
      </description>
    </func>
    <func name="MRF_retryCountSet">
      <arg type="const uint8_t" name="count" traceable="Y">List retry count</arg>
      <return type="int"/>
      <description>Sets the list retry count.
      </description>
    </func>
    <func name="MRF_deauthActionSet">
      <arg type="const uint8_t" name="action" traceable="Y">Deauth Action, either MRF_DO_NOT_ATTEMPT_TO_RECONNECT or MRF_ATTEMPT_TO_RECONNECT.</arg>
      <return type="int"/>
      <description>Sets the action to occur on deauth.
      </description>
    </func>
    <func name="MRF_beaconTimeoutSet">
      <arg type="const uint8_t" name="timeout" traceable="Y">Timeout</arg>
      <return type="int"/>
      <description>Sets the beacon timeout.
      </description>
    </func>
    <func name="MRF_beaconTimeoutActionSet">
      <arg type="const uint8_t" name="action" traceable="Y">Timeout action, either MRF_DO_NOT_ATTEMPT_TO_RECONNECT or MRF_ATTEMPT_TO_RECONNECT.</arg>
      <return type="int"/>
      <description>Sets the action to occur on beacon timeout.
      </description>
    </func>
    <func name="MRF_channelListSet">
      <arg type="const uint8_t* const" name="channels" traceable="Y">Channel list, formed of integers 1-14</arg>
      <arg type="const uint8_t" name="length" traceable="Y">Channel list length</arg>
      <return type="int"/>
      <description>Sets the channel list.
      </description>
    </func>
    <func name="MRF_listenIntervalSet">
      <arg type="const uint16_t" name="interval" traceable="Y">Listen interval</arg>
      <return type="int"/>
      <description>Sets the listen interval.
      </description>
    </func>
    <func name="MRF_dtimIntervalSet">
      <arg type="const uint16_t" name="interval" traceable="Y">DTIM interval</arg>
      <return type="int"/>
      <description>Sets the DTIM interval.
      </description>
    </func>
    <func name="MRF_versionGet">
      <arg type="MRF_VINFO_T* const" name="info" traceable="Y">Struct to be written over</arg>
      <return type="int"/>
      <description>Gets Version and patch numbers.
      </description>
    </func>
    <func name="MRF_domainGet">
      <arg type="uint8_t* const" name="domain" traceable="Y">Buffer to be wriiten onto</arg>
      <return type="int"/>
      <description>Gets the regional domain.
      </description>
    </func>
    <func name="MRF_macGet">
      <arg type="uint8_t* const" name="mac" traceable="Y">Buffer where the MAC address will be written. Must be > 6 octets long</arg>
      <return type="int"/>
      <description>Gets the MAC address.
      </description>
    </func>
    <func name="MRF_connect">
      <return type="int"/>
      <description>Connect to the AP (or if in Soft AP mode, bring up the AP).
      </description>
    </func>
    </interface>
</module>

=== MIPS/meos/support/1/drivers/ns16550a/ns16550a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="ns16550a" prefix="NS16550A" modtype="Special">
	<description>Implements an NS16550A UART driver.</description>
	<imports>kernel</imports>
	<imports>uart</imports>
	<interface>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<include lib="N">meos/uart/uart.h</include>
		<typedef>
			<c>struct NS16550A_tag NS16550A_T</c>(Incomplete) NS16550A UART system object definition.
		</typedef>
		<func name="NS16550A_init">
			<arg type="NS16550A_T *" name="uart" traceable="Y">Pointer to NS16550A UART system object.</arg>
			<arg type="uint8_t *" name="txBuf">Transmission byte buffer.</arg>
			<arg type="size_t" name="txLen">Number of bytes in <code>txBuf</code>.</arg>
			<arg type="uint8_t *" name="rxBuf">Receive byte buffer.</arg>
			<arg type="size_t" name="rxLen">Number of bytes in <code>rxBuf</code>.</arg>
			<arg type="IRQ_DESC_T *" name="irq">IRQ descriptor for specified UART.</arg>
			<return type="void"/>
			<limitations>
				<precondition>((uart != NULL) &amp;&amp; (txBuf != NULL) &amp;&amp; (txLen > 0) &amp;&amp; (rxBuf != NULL) &amp;&amp; (rxLen > 0))</precondition>
			</limitations>
			<description>Initialises the UART described by <code>uart</code> based on the provided configuration.
			</description>
		</func>
		<epilogue>
/* complete the NS16550A_T definition... */
struct NS16550A_tag {
	UART_T	uart;
	uintptr_t	pAddr;
	volatile void*	vAddr;
	uint32_t	clock;
	uint16_t	width;
	uint16_t	pitch;
};
		</epilogue>
	</interface>
</module>

=== MIPS/meos/support/1/drivers/pic32uart/pic32uart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="PIC32 UART" prefix="PIC32_UART" modtype="Special">
	<description>Implements a PIC32 UART driver.</description>
	<imports>kernel</imports>
	<imports>uart</imports>
	<interface>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<include lib="N">meos/uart/uart.h</include>
		<typedef>
			<c>struct PIC32_UART_tag PIC32_UART_T</c>(Incomplete) PIC32 UART system object definition.
		</typedef>
		<func name="PIC32_UART_init">
			<arg type="PIC32_UART_T *" name="uart" traceable="Y">Pointer to PIC32_UART UART system object.</arg>
			<arg type="uint8_t *" name="txBuf">Transmission byte buffer.</arg>
			<arg type="size_t" name="txLen">Number of bytes in <code>txBuf</code>.</arg>
			<arg type="uint8_t *" name="rxBuf">Receive byte buffer.</arg>
			<arg type="size_t" name="rxLen">Number of bytes in <code>rxBuf</code>.</arg>
			<arg type="IRQ_DESC_T *" name="txi">Tx IRQ descriptor for specified UART.</arg>
			<arg type="IRQ_DESC_T *" name="rxi">Rx IRQ descriptor for specified UART.</arg>
			<return type="void"/>
			<limitations>
				<precondition>((uart != NULL) &amp;&amp; (txBuf != NULL) &amp;&amp; (txLen > 0) &amp;&amp; (rxBuf != NULL) &amp;&amp; (rxLen > 0))</precondition>
			</limitations>
			<description>Initialises the UART described by <code>uart</code> based on the provided configuration.
			</description>
		</func>
		<epilogue>
/* complete the PIC32_UART_T definition... */
struct PIC32_UART_tag {
	UART_T	uart;
	uintptr_t	pAddr;
	volatile uint32_t*	regs;
	uint32_t	clock;
};
		</epilogue>
	</interface>
</module>

=== MIPS/meos/support/1/drivers/virtionet/virtionet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "../../../../doc/module.dtd">
<?xml-stylesheet type="text/xsl" href="../../../../doc/doc.xsl"?>
<module name="virtionet" prefix="VIRTIONET" modtype="Special">
	<description>VIRTIONET LWIP driver</description>
	<imports>kernel</imports>
	<imports>lwip</imports>
	<interface>
		<include lib="Y">stdio.h</include>
		<include lib="N">meos/config.h</include>
		<include lib="N">meos/kernel/krn.h</include>
		<include lib="N">lwip/netif.h</include>
		<typedef vis="private"><c>struct VIRTIONET_tag VIRTIONET_T</c>(Incomplete) VIRTIONET system object definition.</typedef>
		<func name="VIRTIONET_dtInit">
			<arg type="VIRTIONET_T *" name="virtionet" traceable="Y">Pointer to VIRTIONET system object.</arg>
			<arg type="IRQ_DESC_T *" name="irq">IRQ descriptor for specified VIRTIONET.</arg>
			<return type="void"/>
			<limitations>
				<precondition>((uart != NULL) &amp;&amp; (irq != NULL))</precondition>
			</limitations>
			<description>Initialises the VIRTIONET described by <code>virtionet</code> based on the provided configuration.
			</description>
		</func>
		<epilogue>
typedef struct {
	MQ_HOSTHEADER_T header;
	VIRTIO_NET_HDR_T nHeader;
	uint8_t data[1526];
} VIRTIONETMSG_T;
/* complete the VIRTIONET_T definition... */
struct VIRTIONET_tag {
	struct netif netif;
	uintptr_t	pAddr;
	void*		ack;
	MQ_MSG_T	rheaders[64];
	KRN_POOL_T	rhpool;
	VIRTIONETMSG_T rmsgs[64];
	KRN_POOL_T	rmpool;
	MQDEVICE_T 	rq;
	uint8_t rring[8192];
	MQ_MSG_T	wheaders[64];
	KRN_POOL_T	whpool;
	VIRTIONETMSG_T wmsgs[64];
	KRN_POOL_T	wmpool;
	MQDEVICE_T 	wq;
	uint8_t wring[8192];
};
		</epilogue>
	</interface>
</module>
